# Generated by Django 3.2.10 on 2021-12-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='login',
            field=models.TextField(blank=True),
        ),
    ]
