# Generated by Django 3.2.10 on 2021-12-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_people_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.TextField()),
            ],
        ),
    ]
