# Generated by Django 3.2.10 on 2021-12-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_login_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Last_url_of_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_url_last', models.URLField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='people',
            name='role',
            field=models.TextField(blank=True),
        ),
    ]
