# Generated by Django 3.2.10 on 2021-12-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20211223_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last_url_of_users',
            name='user_url_last',
            field=models.URLField(max_length=2001),
        ),
    ]
