# Generated by Django 3.2.10 on 2021-12-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_last_url_of_users_user_url_last'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='hirable',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
