# Generated by Django 3.2.10 on 2021-12-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_alter_people_hirable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='hirable',
            new_name='hireable',
        ),
    ]
